services:
  almacen_db:
    image:
      postgres:17
    ports:
      - 5432:5432
    env_file:
      - ./services/db/db.env 
    healthcheck:
      test: ["CMD-SHELL","psql -u $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
    networks:
      - my_private_net

  almacen_api:
    image: 
      almacen_api:latest
    depends_on: 
      - almacen_db
    env_file:
        - ./services/api/.env
    networks:
      - my_private_net

  reverse_proxy:
    image: 
      nginx:latest
    ports: 
      - 80:80
    volumes:
      - ./services/reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - almacen_api
    networks:
      - my_private_net
      - my_public_net

networks:
  my_private_net:
    internal: true 
  my_public_net:
    driver: bridge
